name: CI

on:
  push:

jobs:
  build_and_test:
    name: Build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - uses: actions/checkout@master

      - name: Install ${{ matrix.rust }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true

      - name: check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --bins --tests

      - name: tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all
